name: Python CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install test dependencies
      run: pip install pytest flake8 mypy
    - name: Run linter
      run: flake8 .
    - name: Run type checker
      run: mypy .
    - name: Run pytest
      run: pytest -vv

    - name: Generate specs output
      run: python -m pyspec2openapi examples/config.yml examples/out.yml
    - name: Check specs out is unchanged
      run: |
        if [ -z "$(git status --porcelain)" ]; then 
          echo "Working directory clean"
        else 
          echo "Uncommitted changes"
          git --no-pager diff
          exit 1
        fi

